In [32]:
import torch
import numpy as np

In [14]:
device = "cuda" if torch.cuda.is_available() else "cpu"

## Create tensor

In [16]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype = torch.float32,
                        device=device)

print(my_tensor)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [17]:
print(my_tensor.shape)

torch.Size([2, 3])


## Other common initialization methods

In [7]:
# creates a 3*3 tensor. It's empty or unitialize. Values can be random
x = torch.empty(size = (3, 3))
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [8]:
# random values in uniform distribution
x = torch.rand([3, 3])
print(x)

tensor([[0.4870, 0.9756, 0.3624],
        [0.3807, 0.5629, 0.0426],
        [0.6654, 0.8029, 0.9734]])


In [9]:
x = torch.ones([3, 3])
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [10]:
# identity matrix
x = torch.eye(5, 5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [11]:
x = torch.arange(start = 0, end = 5, step = 1)
print(x)

tensor([0, 1, 2, 3, 4])


In [13]:
x = torch.linspace(start = 0.1, end = 1, steps = 10)
print(x)

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])


In [18]:
x = torch.empty(size = (1, 5)).normal_(mean = 0, std = 1)
print(x)

tensor([[ 0.5244,  0.7119,  0.3115,  2.1574, -1.7818]])


In [20]:
x = torch.empty(size = (1, 5)).uniform_( 0, 1)
print(x)

tensor([[0.7387, 0.9702, 0.8233, 0.7107, 0.6529]])


In [22]:
x = torch.diag(torch.ones(3))
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


## How to initialize and convert tensors to other types(int, float, double)

In [23]:
tensor = torch.arange(4) #int64 by default
print(tensor)

tensor([0, 1, 2, 3])


In [25]:
# convert to bool
print(tensor.bool())

tensor([False,  True,  True,  True])


In [26]:
# create int 16
print(tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [27]:
# create int 64
print(tensor.long())

tensor([0, 1, 2, 3])


In [28]:
# float 16
print(tensor.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)


In [29]:
# float 32 - most useful
print(tensor.float())

tensor([0., 1., 2., 3.])


In [30]:
# float 64
print(tensor.double())

tensor([0., 1., 2., 3.], dtype=torch.float64)


### Array to tensor conversion and vice versa



In [38]:
np_array = np.zeros((5, 5))
print(np_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [37]:
# numpy to tensor
tensor = torch.from_numpy(np_array)
print(tensor)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)


In [39]:
# tensor to numpy
np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


## Tensor Math and comparison operations

In [40]:
x =torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

#### Addition

In [41]:
# method 1
z1 = torch.empty(3)
torch.add(x, y, out = z1)
print(z1)

tensor([10., 10., 10.])


In [42]:
# method 2
z2 = torch.add(x, y)
print(z2)

tensor([10, 10, 10])


In [43]:
# method 3 - best
z = x + y
print(z)

tensor([10, 10, 10])


#### Subtraction

In [45]:
z = x - y
print(z)

tensor([-8, -6, -4])


#### Division

In [46]:
# element wise divison having same shape
z = torch.true_divide(x, y)
print(z)

tensor([0.1111, 0.2500, 0.4286])


#### inplace operations

In [48]:
t = torch.zeros(3)
# inpace method
t.add_(x)

tensor([1., 2., 3.])

**Note:**

Any method ending with _ performs inplace operation

In [52]:
# method 2
t += x
print(t)

tensor([2., 4., 6.])


#### Exponentiation


In [53]:
z = x.pow(2) # element wise
print(z)

tensor([1, 4, 9])


In [54]:
# method 2
 # element wise
z1 = x ** 2

print(z1)

tensor([1, 4, 9])


#### matrix multiplication

In [55]:

# element wise
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2) # 2 * 3
print(x3)

tensor([[0.9741, 1.2273, 0.5444],
        [1.0016, 1.4294, 0.7795]])


In [56]:
# method 2
x4 = x1.mm(x2)
print(x4)

tensor([[0.9741, 1.2273, 0.5444],
        [1.0016, 1.4294, 0.7795]])


#### matrix exponentiation

In [57]:
matrix_exp = torch.rand(5, 5)
print(matrix_exp.matrix_power(3))

tensor([[1.2531, 0.9977, 1.2284, 0.9895, 0.7502],
        [1.5261, 1.1325, 1.4190, 1.0067, 0.9772],
        [1.5055, 0.8381, 0.9520, 0.7671, 0.8565],
        [1.9606, 1.2408, 1.4104, 1.1990, 1.1008],
        [1.9894, 1.1493, 1.6543, 1.3299, 1.1247]])


#### Element wise multiplication

In [58]:
z = x * y
print(z)

tensor([ 9, 16, 21])


#### Dot product

In [60]:
z =torch.dot(x, y)
print(z)

tensor(46)


#### Batch Matrix Multiplication

In [62]:
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p)) 
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n, p)
print(out_bmm)

tensor([[[4.4010, 3.4102, 3.9444,  ..., 3.5563, 5.4540, 5.4769],
         [5.1156, 4.5491, 5.5155,  ..., 4.5912, 5.7291, 6.4793],
         [6.0981, 4.7001, 5.2451,  ..., 5.2124, 6.6487, 6.3466],
         ...,
         [5.0679, 3.7965, 4.7023,  ..., 3.5277, 5.4653, 5.0944],
         [5.0086, 3.9904, 4.6974,  ..., 3.5192, 4.6662, 5.4223],
         [6.5281, 4.6867, 5.2914,  ..., 5.0233, 6.5241, 6.4616]],

        [[5.4462, 6.8053, 6.5670,  ..., 5.3744, 4.7932, 4.8944],
         [5.9870, 7.1073, 6.0760,  ..., 5.2810, 5.4743, 4.9016],
         [5.2375, 5.9573, 5.8051,  ..., 4.8224, 4.1000, 3.7179],
         ...,
         [5.4145, 6.1719, 5.2063,  ..., 4.8420, 4.5446, 3.7669],
         [4.4598, 5.2256, 4.9988,  ..., 4.7895, 5.0204, 4.6099],
         [3.6556, 4.6190, 4.4230,  ..., 3.8739, 3.4841, 3.3421]],

        [[6.3458, 5.3176, 5.8893,  ..., 5.1135, 6.1485, 5.0478],
         [5.9265, 5.5611, 5.0136,  ..., 5.4404, 5.0278, 4.6143],
         [5.6495, 6.0007, 5.7654,  ..., 5.2770, 5.5332, 5.

## Broadcasting

In [64]:
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))
print(x1)

tensor([[0.6061, 0.1613, 0.2191, 0.6402, 0.3658],
        [0.6930, 0.1074, 0.2751, 0.4613, 0.6052],
        [0.3726, 0.3166, 0.8873, 0.5271, 0.6847],
        [0.7856, 0.8602, 0.7281, 0.6050, 0.9614],
        [0.3520, 0.5255, 0.1223, 0.0819, 0.3731]])


In [65]:
print(x2)

tensor([[0.6316, 0.7195, 0.6445, 0.4599, 0.0131]])


In [66]:
# x2 will match the shape of x1 in broadcasting 
z = x1 - x2
print(z)

tensor([[-0.0254, -0.5582, -0.4254,  0.1803,  0.3527],
        [ 0.0614, -0.6120, -0.3695,  0.0014,  0.5922],
        [-0.2590, -0.4028,  0.2428,  0.0672,  0.6716],
        [ 0.1541,  0.1408,  0.0836,  0.1451,  0.9484],
        [-0.2796, -0.1939, -0.5223, -0.3780,  0.3600]])


In [68]:
## Other Tensor Operations
print(x)
# specify the dimension for summation
sum_x = torch.sum(x, dim = 0)
print(sum_x)

tensor([1, 2, 3])
tensor(6)


In [69]:
abs_x = torch.abs(x)
print(abs_x)

tensor([1, 2, 3])


In [70]:
sorted_y, indices = torch.sort(y, dim = 0, descending = False)

In [ ]:
# value < 0 will be 0. just like RELU function
z = torch.clamp(x, min = 0)