## Perceptron implementation using step function

Reference: DS full stack sachin
    
https://learn.ineuron.ai/lesson/9th-Jan-Perceptron-Implementation/61dbca476231938ea0e6fbe3/course/Full-Stack-Data-Science-Feb'21-Batch/61b30b40b733d139bc0e7fd5/batch/61b30b40b733d139bc0e6fe5#

In [1]:
import os
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

import joblib
from matplotlib.colors import ListedColormap

plt.style.use("fivethirtyeight")

In [37]:
class Perceptron:
    
    def __init__(self, eta: float=None, epochs: int=None):
        
        # 3 random value for W0(bias), w1, w2 weights
        # 1e-4 = 10^-4
        self.weights = np.random.randn(3) * 1e-4
        
        # learning rate
        self.eta = eta
        # iterations
        self.epochs = epochs 
   
    # private method. Hence it starts with underscore
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        # we use step function as activation function
        return np.where(z > 0, 1, 0)
        
    #train the model
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        # concat(np.c_) both "input X matrix" with "bias". We take all intial values in bias matrix as -1 
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print('--'*10)
            print(f"for epoch : {epoch + 1}" )
            print('--'*10)
            #multiply input with weights
            z = self._z_outcome(X_with_bias, self.weights)
            
            #compute y_hat using activation function
            y_hat = self.activation_function(z)
            
            print(f"predicted value after forward pass: \n{y_hat}")
            
            #compute error
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            #update weight(backpropagation)
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            
            print(f"updated weightd after epoch : {epoch + 1}/{self.epochs} : \n{self.weights}")
            print(f"##"*10)
        

    def predict(self, X):
        # in predict we don't use self.X since we don't want previous X value
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]

        z = self._z_outcome(X_with_bias, self.weights)
        
        # we use only forward pass in prediction
        return self.activation_function(z)

In [38]:
OR_GATE = {
    "x1" : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    "y" : [0 , 1, 1, 1]
}

df_OR_GATE = pd.DataFrame(OR_GATE)

df_OR_GATE

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  1

In [39]:
def prepare_data(df, target_col = 'y'):
    #drop target col from input matrix
    X = df.drop(target_col, axis = 1)
    
    y = df[target_col]
    
    return X, y

In [40]:
X, y = prepare_data(df_OR_GATE)


ETA = 0.1

EPOCHS = 10

model_or_gate = Perceptron(eta= ETA, epochs= EPOCHS)


model_or_gate.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch : 1
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weightd after epoch : 1/10 : 
[0.00010552 0.000187   0.09979777]
####################
--------------------
for epoch : 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    1
Name: y, dtype: int64
updated weightd after epoch : 2/10 : 
[ 0.20010552  0.200187   -0.20020223]
####################
--------------------
for epoch : 3
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
updated weightd after epoch : 3/10 : 
[ 0.20010552  0.200187   -0.10020223]
####################
--------------------
for epoch : 4
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3    0
Name: y, dtype:

In [34]:
model_or_gate.predict(X=[[0,1]])

array([1])

In [36]:
X

x1  x2
0   0   0
1   0   1
2   1   0
3   1   1

In [35]:
model_or_gate.predict(X)

array([0, 1, 1, 1])

In [41]:
# for AND gate

AND_GATE = {
    "x1" : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    "y" : [0 , 0, 0, 1]
}

df_AND_GATE = pd.DataFrame(AND_GATE)

df_AND_GATE

x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [42]:
X, y = prepare_data(df_AND_GATE)


ETA = 0.1

EPOCHS = 10

model_or_gate = Perceptron(eta= ETA, epochs= EPOCHS)


model_or_gate.fit(X, y)

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch : 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weightd after epoch : 1/10 : 
[ 0.09995492  0.10003158 -0.09991844]
####################
--------------------
for epoch : 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weightd after epoch : 2/10 : 
[-4.50847731e-05  3.15758147e-05  2.00081564e-01]
####################
--------------------
for epoch : 3
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weightd after epoch : 3/10 : 
[0.09995492 0.10003158 0.10008156]
####################
--------------------
for epoch : 4
--------------------
predicted value after forward pass: 
[0 0 0 1]
error: 
0    0
1    0
2    0
3    0
Nam

## Note: This will not work for XOR as it is non linearly separable unlike OR and AND which are linearly separable


## Conclusion: Perceptron is suitable only for linearly separable data and not non linearly separable dataj

## Solution: use more no. of hidden layers. Hence we go with ANN instead of perceptron
